name: kylewm.com
description: Kyle's personal blog
source: ./
destination: ./_site
permalink: /blog/:categories/:year/:month/:day/:title/
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: nil
    coderay_css: class